### ISSUE TITLE
Question: Programatically preventing navigation

### ISSUE THREAD

**Issue by felixSchl** [coot/purescript-cofree-react-router#6]
Hey, I am building a component that let's the user make some changes which remain uncommitted until the user hits "save". Currently I keep the state for those changes with the component as no other system should care about this state at this point. The only problem I see is that any links that change navigation will then erase that state. What would be neat is if I could prompt the user upon leaving the route (page) that there are unsaved local changes. For more context, this stackoverflow post does essentially what I am after: https://stackoverflow.com/a/41460856/2954634.

**Comment by coot** [comment]
There is no mechanism for that in the router. I've been thinking about this, which is also important for transitions, but I haven't time to do that yet.  One needs to rebuild the router since this version is stateless. 

What you can do is to implement a `link` component which can track some external state and prevent routing if things are not supposed to happen.

**Comment by felixSchl** [comment]
I've been thinking about doing it in `link`, too, which would require me know about each page's state in the top-level. Not necessarily bad and might have some positive effects as well, but I think there might be room for each route to have some state that the router knows about. I need to get cozy with `Cofree` first before I can really understand the code :)

**Comment by coot** [comment]
If you need to have a link that works for every route then indeed it might be easier to do that in the router. You could have a `link` that is aware of the router state which indeed is a cofree. There are some combinators to querry it, but you might need something more generic.

I will close the issue, but I am happy to discuss it further.
